sudo: false
language: node_js
node_js: 8
script: npm run setup
cache:
  directories:
    - /home/travis/.cypress/Cypress
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - v2
